### ISSUE TITLE
rename branches

### ISSUE THREAD

**Issue by lemmyg** [marcosfad/mbp-ubuntu#92] opened 2023-06-20 06:54 UTC
it would be better if we rename branches:
jammy:
ubuntu-22.04
kubuntu-22.04
mainline:
ubuntu-23.04
kubuntu-23.04

what do you think?

**Comment by AdityaGarg8** [comment] 2023-06-21 02:27
Tbh I was thinking of ubuntu-LTS and ubuntu-Mainline, else well shall have to change the branch names every time a new version of Ubuntu comes, and update the CI accordingly

**Comment by lemmyg** [comment] 2023-06-21 06:12
I dont know   I like to be specific like 22.04. same as when we release the iso. About CI, change it every 6 months is not a big deal.

**Comment by lemmyg** [comment] 2023-06-21 06:13
By the way, when you have spare time, could you please have a look why the CI is failing?

**Comment by lemmyg** [comment] 2023-06-21 06:21
The good thing of having Ubuntu versions name is that you need create a new
branch every new version and thats allows user build an old version if they
need to

**Comment by AdityaGarg8** [comment] 2023-06-21 07:32
> By the way, when you have spare time, could you please have a look why the CI is failing?

Only the Mainline part is failing, as the Mainline branch already has the version the CI is trying to push, the ISO bit is the one that should succeed. It although was not releasing the iso, which I’ve fixed.

**Comment by lemmyg** [comment] 2023-06-22 11:37
So are we good now?
I hope you saw my comment in chat  about 6.3.9. we may need to skip it

**Comment by AdityaGarg8** [comment] 2023-06-23 12:37
*sigh*, we’ll have to find the patch causing regression now.

**Comment by lemmyg** [comment] 2023-07-08 07:48
HI @AdityaGarg8 ,
I was jammy CI and I don't understand why it mainline and jobs. For example mainlain branch has only iso. Should we remove Kubuntumainline job for kubuntujammy?
Thanks

**Comment by AdityaGarg8** [comment] 2023-07-08 07:57
I didn’t understand what you mean?

**Comment by lemmyg** [comment] 2023-07-08 07:59
Some branches have 2 jobs in CI and others just one.
Why is that?

**Comment by lemmyg** [comment] 2023-07-08 08:01
Just try to find out why Kubuntumainline CI is not working

**Comment by AdityaGarg8** [comment] 2023-07-08 08:04
Like I change the kernel version in the jammy branch, the other job automatically changes it in the mainline branch. The mainline branch doesn't need this job.

**Comment by AdityaGarg8** [comment] 2023-07-08 09:34
Looks like I closed it by mistake

**Comment by lemmyg** [comment] 2023-07-08 10:46
Cool, I thought something had bothered you.

**Comment by AdityaGarg8** [comment] 2023-07-08 10:51
Btw what's wrong with the CI?

**Comment by lemmyg** [comment] 2023-07-08 10:54
I made to the Kubuntu mainline branch. Still we didn't generate any iso for
it. Last time failed.

**Comment by AdityaGarg8** [comment] 2023-07-08 10:57
Both Kubuntu 22.04 and 23.04 are released in the latest release. Can you check again?

________________________________

**Comment by lemmyg** [comment] 2023-07-08 11:10
Oh yes sorry.
All good then

**Closed as completed** 2023-07-19 05:36 UTC
